=== folio-org/mod-circulation-storage/ramls/schema/fixed-due-date-schedule.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "A set of date ranges for materials checkout and their associated due dates.",
  "properties": {
    "id": {
      "description": "Unique ID (generated UUID)",
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "schedules": {
      "id": "schedules",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "schedule.json"
      }
    }
  },
  "additionalProperties": false
}

=== folio-org/mod-circulation-storage/ramls/examples/fixed-due-date-schedule.json
{
  "id": "d9cd0bed-1b49-4b5e-a7bd-064b8d177231",
  "name": "Fall Semester 2017 Due Date Schedule",
  "description": "An example fixed due date schedule",
  "schedules": [
    {
      "from": "2017-08-18",
      "to": "2017-12-05",
      "due": "2017-12-14"
    },
    {
      "from": "0000-00-00",
      "to": "0000-00-00",
      "due": "0000-00-00"
    }
  ]
}
