=== folio-org/mod-circulation-storage/ramls/schema/loan-policy.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "loanable" : {
      "type": "boolean"
    },
    "loansPolicy" : {
      "type": "object",
      "properties": {
        "profileId": {
          "type": "string"
        },
        "period": {
          "type": "object",
          "$ref" : "period.json"
        },
        "closedLibraryDueDateManagementId": {
          "type": "string"
        },
        "existingRequestsPeriod": {
          "type": "object",
          "$ref" : "period.json"
        },
        "gracePeriod": {
          "type": "object",
          "$ref" : "period.json"
        }
      }
    },
    "renewable": {
      "type": "boolean"
    },
    "renewalsPolicy": {
      "type": "object",
      "properties": {
        "unlimited": {
          "type": "boolean"
        },
        "numberAllowed": {
          "type": "number"
        },
        "renewFromId": {
          "type": "string"
        },
        "differentPeriod": {
          "type": "boolean"
        },
        "period": {
          "type": "object",
          "$ref" : "period.json"
        }
      }
    }
  },
  "additionalProperties": false,
  "required": ["loanable", "renewable"]
}

=== folio-org/mod-circulation-storage/ramls/examples/loan-policy.json
{
  "id" : "d9cd0bed-1b49-4b5e-a7bd-064b8d177231",
  "name" : "Example Loan Policy",
  "description" : "An example loan policy",
  "loanable" : true,
  "loansPolicy" : {
    "profileId" : "ROLLING",
    "period" : {
      "duration" : 1,
      "intervalId" : "MONTH"
    },
    "closedLibraryDueDateManagementId" : "KEEP_CURRENT_DATE",
    "existingRequestsPeriod" : {
      "duration" : 1,
      "intervalId" : "WEEK"
    },
    "gracePeriod" : {
      "duration" : 7,
      "intervalId" : "DAYS"
    }
  },
  "renewable" : true,
  "renewalsPolicy" : {
    "unlimited" : true,
    "renewFromId" : "CURRENT_DUE_DATE",
    "differentPeriod" : true,
    "period" : {
      "duration" : 30,
      "intervalId" : "DAYS"
    }
  }
}

=== folio-org/mod-circulation-storage/reference-data/loan-policy-storage/loan-policies/one-hour.json
{
  "id" : "43198de5-f56a-4a53-a0bd-5a324418967a",
  "name" : "One Hour",
  "loanable" : true,
  "loansPolicy" : {
    "profileId" : "Rolling",
    "period" : {
      "duration" : 1,
      "intervalId" : "Hours"
    },
    "closedLibraryDueDateManagementId" : "CURRENT_DUE_DATE_TIME"
  },
  "renewable" : true,
  "renewalsPolicy" : {
    "unlimited" : false,
    "numberAllowed": 3,
    "renewFromId" : "SYSTEM_DATE",
    "differentPeriod" : false
  }
}

=== folio-org/mod-circulation-storage/sample-data/templates/loan-policy.json
{
  "id" : "",
  "name" : "",
  "description" : "",
  "loanable" : true,
  "loansPolicy" : {
    "profileId" : "",
    "period" : {
      "duration" : 0,
      "intervalId" : ""
    },
    "closedLibraryDueDateManagementId" : "",
    "existingRequestsPeriod" : {
      "duration" : 0,
      "intervalId" : ""
    },
    "gracePeriod" : {
      "duration" : 0,
      "intervalId" : ""
    }
  },
  "renewable" : true,
  "renewalsPolicy" : {
    "unlimited" : true,
    "renewFromId" : "",
    "differentPeriod" : true,
    "period" : {
      "duration" : 0,
      "intervalId" : ""
    }
  }
}
